<?php

namespace Mjarestad\DHL\QuotePrice;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'PallsaldoTransactions' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\PallsaldoTransactions',
            'PallsaldoTransactionsResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\PallsaldoTransactionsResponse',
            'PallsaldoTransactionsResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\PallsaldoTransactionsResult',
            'Pallsaldo' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\Pallsaldo',
            'PallsaldoResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\PallsaldoResponse',
            'PallsaldoResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\PallsaldoResult',
            'QuoteForPriceForModuleCountry' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPriceForModuleCountry',
            'QuoteForPriceForModuleCountryResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPriceForModuleCountryResponse',
            'QuoteForPrice' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPrice',
            'QuoteForPriceResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPriceResponse',
            'GetQuotableAccount' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccount',
            'GetQuotableAccountResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccountResponse',
            'GetQuotableAccountForModuleCountry' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccountForModuleCountry',
            'GetQuotableAccountForModuleCountryResponse' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccountForModuleCountryResponse',
            'Credentials' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\Credentials',
            'tQuote' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TQuote',
            'tDHLB2C' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLB2C',
            'tDHLC2B' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLC2B',
            'tDHLEuropack' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLEuropack',
            'tDHLEuroplus' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLEuroplus',
            'tDHLExpress' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLExpress',
            'tDHLHomeDeliveryDhlTerminal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLHomeDeliveryDhlTerminal',
            'tDHLHomeDeliveryDhlTerminalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLHomeDeliveryDhlTerminalReturn',
            'tDHLHomeDeliveryExternalTerminal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLHomeDeliveryExternalTerminal',
            'tDHLHomeDeliveryExternalTerminalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLHomeDeliveryExternalTerminalReturn',
            'tDHLPall' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLPall',
            'tDHLParti' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLParti',
            'tDHLStycke' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDHLStycke',
            'tDkEuroConnect' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDkEuroConnect',
            'tDkEuroConnectDomestic' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDkEuroConnectDomestic',
            'tDkEuroLineDomestic' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDkEuroLineDomestic',
            'tEurapid' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TEurapid',
            'tEuroConnect' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TEuroConnect',
            'tEuropremiumSE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TEuropremiumSE',
            'tNorskInnland' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TNorskInnland',
            'tWeightNO' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightNO',
            'tVolumeNO' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolumeNO',
            'tLoadingmeterNO' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeterNO',
            'tCODAmount' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TCODAmount',
            'tPaketExport' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TPaketExport',
            'tParcelConnect' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TParcelConnect',
            'tSverigePall' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSverigePall',
            'tSwednet' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSwednet',
            'tWeight4' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight4',
            'tVolume4' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume4',
            'tSenderReceiver4' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver4',
            'tValues4' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues4',
            'tOptions4' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions4',
            'tOwnSurCharge' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOwnSurCharge',
            'tOwnSurChargePerc' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOwnSurChargePerc',
            'tCODAmountSE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TCODAmountSE',
            'tInsuaranceAmountSEKOption' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TInsuaranceAmountSEKOption',
            'tNumberOfRepetisionsOption' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TNumberOfRepetisionsOption',
            'tWeight8' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight8',
            'tSenderReceiver8' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver8',
            'tValues8' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues8',
            'tOptions8' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions8',
            'tWeight7' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight7',
            'tVolume7' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume7',
            'tSenderReceiver7' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver7',
            'tValues7' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues7',
            'tOptions7' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions7',
            'tSenderReceiver_TD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver_TD',
            'tDimensions_TD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDimensions_TD',
            'tWeight_TD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight_TD',
            'tVolume_TD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume_TD',
            'tValues_TD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues_TD',
            'tCODAmountTD' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TCODAmountTD',
            'tWeightHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightHomeDelivery',
            'tVolumeHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolumeHomeDelivery',
            'tLoadingmeterHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeterHomeDelivery',
            'tSenderReceiverHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiverHomeDelivery',
            'tValuesHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValuesHomeDelivery',
            'tOptionsHomeDelivery' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptionsHomeDelivery',
            'tWeightHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightHomeDeliveryReturn',
            'tVolumeHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolumeHomeDeliveryReturn',
            'tLoadingmeterHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeterHomeDeliveryReturn',
            'tSenderReceiverHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiverHomeDeliveryReturn',
            'tValuesHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValuesHomeDeliveryReturn',
            'tOptionsHomeDeliveryReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptionsHomeDeliveryReturn',
            'tWeightHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightHomeDeliveryExternal',
            'tVolumeHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolumeHomeDeliveryExternal',
            'tLoadingmeterHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeterHomeDeliveryExternal',
            'tSenderReceiverHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiverHomeDeliveryExternal',
            'tValuesHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValuesHomeDeliveryExternal',
            'tOptionsHomeDeliveryExternal' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptionsHomeDeliveryExternal',
            'tWeightHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightHomeDeliveryExternalReturn',
            'tVolumeHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolumeHomeDeliveryExternalReturn',
            'tLoadingmeterHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeterHomeDeliveryExternalReturn',
            'tSenderReceiverHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiverHomeDeliveryExternalReturn',
            'tValuesHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValuesHomeDeliveryExternalReturn',
            'tOptionsHomeDeliveryExternalReturn' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptionsHomeDeliveryExternalReturn',
            'tWeight3' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight3',
            'tSenderReceiver3' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver3',
            'tValues3' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues3',
            'tOptions3' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions3',
            'tWeight2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight2',
            'tVolume2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume2',
            'tLoadingmeter2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeter2',
            'tLongGoods2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLongGoods2',
            'tLength2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength2',
            'tWidth2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth2',
            'tSenderReceiver2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver2',
            'tValues2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues2',
            'tOptions2' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions2',
            'tWeight1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight1',
            'tVolume1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume1',
            'tLoadingmeter1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeter1',
            'tLongGoods1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLongGoods1',
            'tWeightLG' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeightLG',
            'tLength1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength1',
            'tWidth1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth1',
            'tSenderReceiver1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver1',
            'tValues1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues1',
            'tOptions1' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions1',
            'tSenderReceiver_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver_EC',
            'tDimensions' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDimensions',
            'tWeight_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight_EC',
            'tVolume_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume_EC',
            'tLoadingmeter_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeter_EC',
            'tLength_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength_EC',
            'tWidth_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth_EC',
            'tHeight_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\THeight_EC',
            'tOptions9' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions9',
            'tCOD_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TCOD_EC',
            'tInsurance_EC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TInsurance_EC',
            'tSenderReceiver_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver_ER',
            'tWeight_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight_ER',
            'tVolume_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume_ER',
            'tLoadingmeter_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeter_ER',
            'tLength_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength_ER',
            'tWidth_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth_ER',
            'tHeight_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\THeight_ER',
            'tInsurance_ER' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TInsurance_ER',
            'tWeight_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight_PE',
            'tVolume_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume_PE',
            'tSenderReceiver_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver_PE',
            'tDimensions_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDimensions_PE',
            'tLength_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength_PE',
            'tWidth_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth_PE',
            'tHeight_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\THeight_PE',
            'tOptions_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions_PE',
            'tInsurance_PE' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TInsurance_PE',
            'tWeight_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight_PC',
            'tVolume_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume_PC',
            'tSenderReceiver_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver_PC',
            'tDimensions_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TDimensions_PC',
            'tLength_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength_PC',
            'tWidth_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth_PC',
            'tHeight_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\THeight_PC',
            'tOptions_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions_PC',
            'tInsurance_PC' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TInsurance_PC',
            'tWeight6' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight6',
            'tSenderReceiver6' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver6',
            'tValues6' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues6',
            'tOptions6' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions6',
            'tWeight5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWeight5',
            'tVolume5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TVolume5',
            'tLoadingmeter5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLoadingmeter5',
            'tLongGoods5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLongGoods5',
            'tLength5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TLength5',
            'tWidth5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TWidth5',
            'tSenderReceiver5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TSenderReceiver5',
            'tValues5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TValues5',
            'tOptions5' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TOptions5',
            'QuoteForPriceForModuleCountryResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPriceForModuleCountryResult',
            'ResponseRow' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\ResponseRow',
            'QuoteForPriceResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QuoteForPriceResult',
            'GetQuotableAccountResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccountResult',
            'QAResponseRow' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\QAResponseRow',
            'tProduct' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\TProduct',
            'GetQuotableAccountForModuleCountryResult' => '\\Mjarestad\\DHL\\QuotePrice\\StructType\\GetQuotableAccountForModuleCountryResult',
        );
    }
}
